# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 611114f2fb25fee69deccff61fc66315c4077c7adb24e445afa451b41e991692ee074a9a5aab549eb8a5837a46ff94b29858b728a0d0924f7374d0ee605ca086

test:
  secret_key_base: 27492e67795040fb2c91a4b108c7c295757755625609ae111eaae80ccf933fb25eaa7f2c92cfe9d6f07a3940f0016d512343913495676b2f6339c4cff36cfb00

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
